var dataArr = [
    {
        imgUrl : "https://m.media-amazon.com/images/I/41xgPSqzJnL.jpg" ,
        head1 : "Superior: The Return of Race Science",
        head2 : "Angela Saini's Superior: The Return of Race Science",
        details : "When you see how power has shaped the idea of race, then you can start to understand its meaning. For millennia, dominant societies have had the habit of believing their own people to be the best, deep down: the more powerful they become, the more power begins to be framed as natural, as well as cultural. In the twenty-first century, we like to believe that we have moved beyond Scientific racism, that most people accept race as a social construct, not a biological one. But race science is experiencing a revival, fuelled by the misuse of science by certain political groups. Even well-intentioned scientists, through their use of racial Categories in Genetics and medicine, betray their suspicion that race has some basis in biology. In truth, it is no more real than it was hundreds of years ago, when our racial hierarchies were devised by those in power. In Superior, award-winning author Angela Saini explores the concept of race, from its origins to the present day. Engaging with geneticists, anthropologists, historians and social scientists from across the globe, Superior is a rigorous, much-needed examination of the insidious and destructive nature of race science." ,
        price : "407" ,
        author: "Angela Saini" ,
        whyData : "Why you should read Superior: The Return of Race Science by Angela Saini" ,
        whyDetails : "This book has been written by Risto Siilasmaa, who has written books like Transforming NOKIA: The Power of Paranoid Optimism to Lead Through Colossal Change. The books are written in Business, Strategy & Management category. This book is read by people who are interested in reading books in category : Business, Strategy & Management. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Superior: The Return of Race Science" ,
        buyNow : "" ,
        pageNo : "" ,
    } ,
    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41NcBucflHL.jpg" ,
        head1 : "Cfa Level 1 Calculation Workbook: 300 Calculations to Prepare for the Cfa Level 1 Exam (2019 Edition)" ,
        head2 : "Coventry House Publishing's Cfa Level 1 Calculation Workbook: 300 Calculations to Prepare for the Cfa Level 1 Exam (2019 Edition)" ,
        details : "Message from the publisher: This book contains short, concise questions and answers that are intended to reinforce CFA topics already learned. It does not include lengthy paragraph style questions and answers that are provided by the CFA Institute.The CFA Level 1 Calculation Workbook provides 300 calculation questions to prepare for the demanding Chartered Financial Analyst (CFA) Level 1 Exam. Master exam topics with intensive practice in the essential areas you'll find on the test. Whether you're challenging the exam for the first Time or trying again after an unsuccessful attempt, you will learn the critical skills needed to master the exam.Included are 50 question exams for the following topics: - Quantitative Methods- Economic Analysis- Financial Statement Analysis- Corporate Finance & Portfolio Management- Equity & Fixed Income Investments- Derivatives & Alternative InvestmentsAbout the CFA ProgramThe Chartered Financial Analyst (CFA) credential is the most respected and widely recognized investment Management designation in the world. The CFA program provides a strong Foundation of advanced investment analysis and real-world portfolio Management skills that members use through all stages of their careers. By earning the CFA designation, you will join a vast Professional network of more than 135,000 charterholders worldwide, and you'll gain unmatched credibility and career resources." ,
        price : "1905" ,
        author : "Coventry House Publishing" ,
        whyData : "Why you should read Cfa Level 1 Calculation Workbook: 300 Calculations to Prepare for the Cfa Level 1 Exam (2019 Edition) by Coventry House Publishing" ,
        whyDetails: "This book has been written by Coventry House Publishing, who has written books like Cfa Level 1 Calculation Workbook: 300 Calculations to Prepare for the Cfa Level 1 Exam (2019 Edition),Cfa Level 1 Calculation Workbook: 300 Calculations to Prepare for the Cfa Level 1 Exam (2018 Edition),CFA Level 1 Calculation Workbook: 300 Calculations to Prepare for the CFA Level 1 Exam (2017 Edition). The books are written in Business, Strategy & Management category. This book is read by people who are interested in reading books in category : Business, Strategy & Management. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Cfa Level 1 Calculation Workbook: 300 Calculations to Prepare for the Cfa Level 1 Exam (2019 Edition)" ,
    } ,
    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51Yrxqrk3HL.jpg" ,
        head1 : "Untitled" ,
        head2 : "Sudeep Nagarkar's Untitled" ,
        details : "Should I smile because we are friends or cry because we are just friends?Blessed with the gift of the gab, Apurv manages to charm everyone in his company. Like most teenage boys, he longs for a girlfriend but hasn't found one yet. In another part of town, beautiful and popular Amyra leads a flawless life. All the Boys desire her and all the Girls want to be her best friend. A chance encounter with Amyra in the college canteen makes Apurv fall head over heels for her. But it isn't long before he realizes that she is not interested in him, at least not in the way he wants her to be. Can Apurv get Amyra to change her mind before it's too late, or will he be friend-zoned forever?" ,
        price : "126" ,
        author : "	Sudeep Nagarkar" ,
        whyData : "Why you should read Untitled by Sudeep Nagarkar" ,
        whyDetails : "This book has been written by Sudeep Nagarkar, who has written books like Stand By Me!,The Secrets We Keep,Untitled,That’s the Way We Met,Sorry, You’re Not My Type (Marathi). The books are written in Crime, Thriller & Mystery,Contemporary Fiction,Classic Fiction,Romance category. This book is read by people who are interested in reading books in category : Contemporary Fiction. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Untitled" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/417aFAhu12L.jpg" ,
        head1 : "Done Deal: An Insider's Guide to Football Contracts, Multi-Million Pound Transfers and Premier League Big Business" ,
        head2 : "Daniel Geey's Done Deal: An Insider's Guide to Football Contracts, Multi-Million Pound Transfers and Premier League Big Businessvv" ,
        details : "Insightful, enlightening and thought-provoking, leading Premier League lawyer Daniel Geey lifts the lid on the inner workings of modern Football. Whether it is a manager being sacked, the signing of a new star player, Television rights negotiations, player misconduct or multi-million-pound club takeovers, lawyers remain at the heart of all Football Business dealings. Written by leading Premier League lawyer Daniel Geey, who has dealt with all these incidents first hand, this highly accessible book explores the Issues – from pitch to boardroom – that shape the modern game and how these impact leagues, clubs, Players and Fans. Featuring insider anecdotes and expert contributions, Done Deal provides Football Fans with a fresh and authoritative perspective on all off-field Football matters." ,
        price : "1084" ,
        author : "	Daniel Geey" ,
        whyData : "Why you should read Done Deal: An Insider's Guide to Football Contracts, Multi-Million Pound Transfers and Premier League Big Business by Daniel Geey" ,
        whyDetails : "This book has been written by Daniel Geey, who has written books like Done Deal: An Insider's Guide to Football Contracts, Multi-Million Pound Transfers and Premier League Big Business,Done Deal: An Insider's Guide to Football Contracts, Multi-Million Pound Transfers and Premier League Big Business. The books are written in Business, Strategy & Management,Business & Economics category. This book is read by people who are interested in reading books in category : Business & Economics. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Done Deal: An Insider's Guide to Football Contracts, Multi-Million Pound Transfers and Premier League Big Business" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51Jrj19QzcL.jpg" ,
        head1 : "Indian Nuclear Strategy : Confronting the Potential Threat from both China and Pakistan" ,
        head2 : "Sanjay Badri-Maharaj's Indian Nuclear Strategy : Confronting the Potential Threat from both China and Pakistan" ,
        details : "Twenty years after the 1998 nuclear tests and the publication of India's Nuclear Doctrine, India has continued to Face endemic Security challenges from both China and Pakistan. The latter, through the apparent induction of tactical nuclear weapons into the equation and a rapid expansion of its fissile material production capacity has introduced an additional complication into Indian Security calculations while China has become increasingly assertive and intransigent in its conduct towards its neighbours. India's nuclear strategy, facing a changing landscape, has shown some degree of flexibility though this has not been adequately articulated. Furthermore, discussion of India's nuclear strategy, such that it is, has been somewhat one-dimensional with an excessive and, it is argued, unnecessary debate over the stated Indian policy of no-first-use. This book examines India's nuclear strategy as it confronts the potential threat from both China and Pakistan. The potential threats - traditional as well as non-traditional CBRN threats - will be examined as will India's approach to dealing with them. India's nuclear arsenal, its dual purpose civil-military space program and its nascent BMD capability will be explored with a view to informing the reader as to the steps taken by India to confront its nuclear challenges. In addition, the Indian nuclear doctrine and the strategy evolved therefrom is examined to demonstrate the flexibility inherent in the Indian nuclear doctrine while also highlighting certain areas that require attention. By adopting an excessively secretive approach, India has failed to articulate its approach to nuclear strategy. It is perhaps Time that India reconsiders this approach and facilitates a more public and forthright discussion of its nuclear strategy in light of evolving nuclear threats while simultaneously continuing to develop its capabilities so as to deter any potential conflict." ,
        price : "646" ,
        author : "	Sanjay Badri-Maharaj" ,
        whyData : "Why you should read Indian Nuclear Strategy : Confronting the Potential Threat from both China and Pakistan by Sanjay Badri-Maharaj" ,
        whyDetails : "This book has been written by Sanjay Badri-Maharaj, who has written books like Indian Nuclear Strategy : Confronting the Potential Threat from both China and Pakistan. The books are written in International Relations & Globalization category. This book is read by people who are interested in reading books in category : International Relations & Globalization. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Indian Nuclear Strategy : Confronting the Potential Threat from both China and Pakistan" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51pqyKkw96L.jpg" ,
        head1 : "Critical Care Secrets, 6e" ,
        head2 : "Polly E. Parsons MD's Critical Care Secrets, 6e" ,
        details : "For more than 30 years, the highly regarded Secrets Series® has provided students and practitioners in all areas of Health care with concise, focused, and engaging Resources for quick Reference and exam review. Critical Care Secrets, 6th Edition, features the Secrets' popular question-and-answer format that also includes lists, tables, and an easy-to-read style - making Reference and review quick, easy, and enjoyable.Fully updated throughout, with new chapters on neurological monitoring, obesity in the ICU, new ultrasound practices, ICU survivorship, and the latest cardiac Technology such as ventricular assist and percutaneous support devices.Written and fully updated by clinical and thought leaders in Critical Care who have contributed chapters in their areas of expertise.The proven Secrets Series® format gives you the most return for your Time - concise, easy to read, engaging, and highly effective.Covers the full range of essential topics in Critical Care for in-training or practicing professionals, including anatomy, physiology, immunology, and inflammation - fundamentally important topics in the effective care of critically ill patients.Top 100 Secrets and Key Points boxes provide a fast overview of the secrets you must know for success in practice and on exams.Portable size makes it easy to carry with you for quick Reference or review anywhere, anytime.Expert ConsultT eBook version included with purchase. This enhanced eBook experience allows you to search all of the text, figures, and References from the book on a variety of devices." ,
        price : "2239" ,
        author : "	Polly E. Parsons MD" ,
        whyData : "Why you should read Critical Care Secrets, 6e by Polly E. Parsons MD" ,
        whyDetails : "This book has been written by Polly E. Parsons MD, who has written books like Critical Care Secrets: First South Asia Edition,Critical Care Secrets, 6e,Pulmonary/Respiratory Therapy Secrets,Critical Care Secrets, 5e. The books are written in Emergency Medical Services,Critical Care,Reference category. This book is read by people who are interested in reading books in category : Critical Care. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Critical Care Secrets, 6e" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41FiFeflJ3L.jpg" ,
        head1 : "Superbugs – An Arms Race against Bacteria" ,
        head2 : "William Hall's Superbugs – An Arms Race against Bacteria" ,
        details : "Antibiotics are powerful Drugs that can prevent and treat infections, but they are becoming less effective as a result of drug resistance. Superbugs describes this growing global threat, the systematic failures that have led to it, and solutions that governments, industries, and public Health specialists can adopt." ,
        price : "1147" ,
        author : "	William Hall" ,
        whyData : "Why you should read Superbugs – An Arms Race against Bacteria by William Hall" ,
        whyDetails : "This book has been written by William Hall, who has written books like Superbugs – An Arms Race against Bacteria,Wood. The books are written in Economic Policy & Development,Architecture category. This book is read by people who are interested in reading books in category : Economic Policy & Development. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Superbugs – An Arms Race against Bacteria" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41QRbgvLW8L.jpg" ,
        head1 : "The Scandal of the Century: And Other Writings" ,
        head2 : "Gabriel García Márquez's The Scandal of the Century: And Other Writings" ,
        details : "The articles and columns in The Scandal of the Century demonstrate that his forthright, lightly ironical voice just seemed to be there, right from the start. . . . He’s among those rare great fiction writers whose ancillary work is almost always worth finding. . . . He had a way of connecting the souls in all his writing, fiction and nonfiction, to the melancholy static of the universe.” --Dwight Garner, The New York TimesFrom one of the titans of twentieth-century literature, collected here for the first time: a selection of his journalism from the late 1940s to the mid-1980s--work that he considered even more important to his legacy than his universally acclaimed works of fiction.I don't want to be remembered for One Hundred Years of Solitude or for the Nobel Prize but rather for my journalism, Gabriel García Márquez said in the final years of his life. And while some of his journalistic writings have been made available over the years, this is the first volume to gather a representative selection from across the first four decades of his career--years during which he worked as a full-time, often muckraking, and controversial journalist, even as he penned the fiction that would bring him the Nobel Prize in 1982. Here are the first pieces he wrote while working for newspapers in the coastal Colombian cities of Cartagena and Barranquilla . . . his longer, more fictionlike reportage from Paris and Rome . . . his monthly columns for Spain's El País. And while all the work points in style, wit, depth, and passion to his fiction, these fifty pieces are, more than anything, a revelation of the writer working at the profession he believed to be",
        price : "1328" ,
        author : "	Gabriel García Márquez" ,
        whyData : "Why you should read The Scandal of the Century: And Other Writings by Gabriel García Márquez" ,
        whyDetails : "This book has been written by Gabriel García Márquez, who has written books like The Scandal of the Century: And Other Writings,Clandestine in Chile: The Adventures of Miguel Littin (New York Review Books Classics). The books are written in Biographies & Autobiographies,Cinema & Broadcast category. This book is read by people who are interested in reading books in category : Biographies & Autobiographies. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read The Scandal of the Century: And Other Writings" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51BC2ilpWGL.jpg" ,
        head1 : "Revolutionary Desires: Women, Communism and Feminism in India" ,
        head2 : "Ania Loomba's Revolutionary Desires: Women, Communism and Feminism in India" ,
        details : "Revolutionary Desires examines the lives and subjectivities of militant-nationalist and communist Women in India from the late 1920s, shortly after the communist movement took root, to the 1960s, when it fractured. This close study demonstrates how India's Revolutionary Women shaped a new female – and in some cases feminist – political subject in the twentieth century, in collaboration and contestation with Indian nationalist, liberal-feminist, and European left-wing Models of Women hood." ,
        price : "523" ,
        author : "	Ania Loomba" ,
        whyData : "Why you should read Revolutionary Desires: Women, Communism and Feminism in India by Ania Loomba" ,
        whyDetails : "This book has been written by Ania Loomba, who has written books like Revolutionary Desires: Women, Communism and Feminism in India,Shakespeare Race & Colonialism:,Shakespeare, Race, and Colonialism (Oxford Shakespeare Topics). The books are written in Gender Studies,Reference,History category. This book is read by people who are interested in reading books in category : Gender Studies. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Revolutionary Desires: Women, Communism and Feminism in India" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/5193q9jLyHL.jpg" ,
        head1 : "Programming in Python 3: A Complete Introduction to the Python Language" ,
        head2 : "Mark Summerfield's Programming in Python 3: A Complete Introduction to the Python Language" ,
        details : "A Fully Revised Edition Featuring New Material on Coroutines, Debugging, Testing, Parsing, String Formatting, and MorePython 3 is the best version of the language yet: It is more powerful, convenient, consistent, and expressive than ever before. Now, leading Python programmer Mark Summerfield demonstrates how to write code that takes full advantage of Python 3’s features and idioms. Programming in Python 3, Second Edition, brings together all the knowledge you need to write any program, use any standard or third-party Python 3 library, and create New library modules of your own. Summerfield draws on his many years of Python experience to share deep insights into Python 3 development you won’t find anywhere else. He begins by illuminating Python’s “beautiful heart”: the eight key elements of Python you need to write robust, high-performance programs. Building on these core elements, he introduces New topics designed to strengthen your practical expertise–one concept and hands-on example at a time. Coverage includesDeveloping in Python using procedural, object-oriented, and functional Programming paradigmsCreating custom packages and modulesWriting and reading binary, text, and XML files, including optional compression, random access, and text and XML parsingLeveraging advanced data types, collections, control structures, and functionsSpreading program workloads across multiple processes and threadsProgramming SQL Databases and key—value DBM filesDebugging techniques–and using Test Driven Development to avoid bugs in the first placeUtilizing Python’s regular expression mini-language and moduleParsing techniques, including how to use the third-party Parsing and PLY modulesBuilding usable, efficient, GUI-based applicationsAdvanced Programming techniques, including generators, function and class decorators, context managers, descriptors, abstract base classes, met classes, coroutines, and moreFeaturesTable of Contents Chapter 1: Rapid Introduction to Procedural ProgrammingChapter 2: Data TypesChapter 3: Collection Data TypesChapter 4: Control Structures and FunctionsChapter 5: ModulesChapter 6: Object-Oriented ProgrammingChapter 7: File Handling Chapter 8: Advanced Programming TechniquesChapter 9: Debugging, Testing, and ProfilingChapter 10: Processes and ThreadingChapter 11: NetworkingChapter 12: Database ProgrammingChapter 13: Regular Expressions Chapter 14: Introduction to ParsingChapter 15: Introduction to GUI Programming" ,
        price : "522" ,
        author : "	Mark Summerfield" ,
        whyData : "Why you should read Programming in Python 3: A Complete Introduction to the Python Language by Mark Summerfield" ,
        whyDetails : "This book has been written by Mark Summerfield, who has written books like Programming in Python 3: A Complete Introduction to the Python Language. The books are written in Programming Languages category. This book is read by people who are interested in reading books in category : Programming Languages. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Programming in Python 3: A Complete Introduction to the Python Language" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51IiPv7cxoL.jpg" ,
        head1 : "Marvel Studios Character Encyclopedia" ,
        head2 : "Adam Bray's Marvel Studios Character Encyclopedia" ,
        details : "The essential guide to the heroes and villains of the Marvel studios moviesLearn the facts, figures, super-powers and origins of your favourite characters from the Marvel Cinematic Universe (MCU). From the Avengers and Ant-Man to Black Panther and Doctor Strange, this book spans over a decade of action-packed Marvel Studios movie releases. Filled with interesting facts and key information, whether your favourite hero is Captain America, Black Widow, Thor, the Wasp, Iron Man or Gamora, you'll be able to find out all about their story, super-powers, weapons, and much more. It isn't all heroes though; this book includes powerful villains and their followers, sinister spies, brave soldiers, and even ordinary people who find themselves caught up in epic battles!Whatever it is that you want to know, Marvel Studios: Character Encyclopedia will make you an instant Marvel Studios expert. Wondering what Thor's hammer is called*, or where Vision came from? How Iron Man builds his suits, or who Thanos is? Then this is the book for you!*Mjolnir, just in case you were wondering!© 2018 MARVEL" ,
        price : "912" ,
        author : "	Adam Bray" ,
        whyData : "Why you should read Marvel Studios Character Encyclopedia by Adam Bray" ,
        whyDetails : "This book has been written by Adam Bray, who has written books like Marvel Studios Character Encyclopedia,Marvel Studios Visual Dictionary (Dk Marvel),Marvel Studios All Your Questions Answered. The books are written in Cinema & Broadcast category. This book is read by people who are interested in reading books in category : Cinema & Broadcast. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Marvel Studios Character Encyclopedia" ,
    },

     {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51WHPCH6-8L.jpg" ,
        head1 : "IBPS 2019: Specialist Officers HR/Personnel Officer Scale I (Preliminary & Main) 15 Practice Sets" ,
        head2 : "GKP's IBPS 2019: Specialist Officers HR/Personnel Officer Scale I (Preliminary & Main) 15 Practice Sets" ,
        details : "Practice tests are a surefire way to test your preparation level and identify areas of improvement. Continuing with GKP’s mission to provide students with quality preparation material for recruitment tests conducted by IBPS, we have come up with 15 full-length practice sets for the HR/Personnel Officer Examination. All practice sets have been designed along the line of Memory based papers of the actual exams of 2015, 2016 and 2017. There are 10 practice sets for the pre exam and 5 for the main. Each question is supported with detailed answers for understanding concepts more clearly. This book will help students familiarize themselves with the exam pattern and weightage of questions." ,
        price : "186" ,
        author : "	GKP" ,
        whyData : "Why you should read IBPS 2019: Specialist Officers HR/Personnel Officer Scale I (Preliminary & Main) 15 Practice Sets by GKP" ,
        whyDetails : "This book has been written by GKP, who has written books like SBI 2020: Clerical Grade Ph I & II Junior Associates - Guide,RBI (Reserve Bank of India) 2020: Assistant - 15 Practice Sets,TRB 2019-20 : Lecturers Engineering - Electrical & Electronics Engineering,GATE 2020 : Mechanical Engineering - Solved Papers 2000-2019,Coal India Ltd. 2019-20: Management Trainee - Personnel & HR. The books are written in Bank Clerical Exams,Bank Specialist Officers Exams,Teacher Recruitment Exams,GATE,Government Exams category. This book is read by people who are interested in reading books in category : Bank Specialist Officers Exams. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read IBPS 2019: Specialist Officers HR/Personnel Officer Scale I (Preliminary & Main) 15 Practice Sets" ,
    },

     {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41clYfBElPL.jpg" ,
        head1 : "Yoga Therapy for Arthritis: A Whole-Person Approach to Movement and Lifestyle" ,
        head2 : "Dr Steffany Moonaz's Yoga Therapy for Arthritis: A Whole-Person Approach to Movement and Lifestyle" ,
        details : "Yoga therapy is commonly used for the Management of arthritis, but often focusses exclusively on adaptation of the physical poses and on structural solutions. This book moves beyond the traditional routines to present Yoga as a lifestyle designed to improve quality of life and overall well-being for individuals living with arthritis and rheumatic conditions. By incorporating the Ancient practices of Yoga as both physical and mental exercises involving a model of 5-koshas or sheaths (physical, energetic, mental/emotional, wisdom, and spiritual), the Yoga therapy practice presented here will help reduce pain and shift the perspective of the individual living with arthritis. This therapy uses a whole-person approach that employs a broad range of Tools to address the biopsychosocial effects of arthritis through the application of Yoga practices and philosophy. Useful as a guide for People living with arthritis, this book is full of inspiration for self care along with instructions for Yoga teachers and medical professionals to guide their clients using this whole-person perspective." ,
        price : "2001" ,
        author : "	Dr Steffany Moonaz" ,
        whyData : " Why you should read Yoga Therapy for Arthritis: A Whole-Person Approach to Movement and Lifestyle by Dr Steffany Moonaz" ,
        whyDetails : "This book has been written by Dr Steffany Moonaz, who has written books like Yoga Therapy for Arthritis: A Whole-Person Approach to Movement and Lifestyle. The books are written in Healthy Living & Wellness category. This book is read by people who are interested in reading books in category : Healthy Living & Wellness. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Yoga Therapy for Arthritis: A Whole-Person Approach to Movement and Lifestyle" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/418me3LZnIL.jpg" ,
        head1 : "Mastering PostgreSQL 11: Expert techniques to build scalable, reliable, and fault-tolerant database applications, 2nd Edition" ,
        head2 : "Hans-Jurgen Schonig's Mastering PostgreSQL 11: Expert techniques to build scalable, reliable, and fault-tolerant database applications, 2nd Edition" ,
        details : "Master the capabilities of PostgreSQL 11 to efficiently manage and maintain your database Key Features Master advanced concepts of PostgreSQL 11 with real-world datasets and examples Explore query parallelism, data replication, and database performance while working with larger datasets Extend the functionalities of your PostgreSQL instance to suit your organization's needs with minimal effort Book DescriptionThis second edition of Mastering PostgreSQL 11 helps you build Dynamic database solutions for enterprise applications using the latest release of PostgreSQL, which enables database analysts to Design both the physical and technical aspects of the system Architecture with ease. This book begins with an introduction to the newly released features in PostgreSQL 11 to help you build efficient and fault-tolerant PostgreSQL applications. You'll examine all of the advanced aspects of PostgreSQL in detail, including logical replication, database clusters, performance tuning, monitoring, and user management. You will also Work with the PostgreSQL optimizer, configuring PostgreSQL for high speed, and see how to move from Oracle to PostgreSQL. As you progress through the chapters, you will cover transactions, locking, indexes, and optimizing queries to improve performance. Additionally, you'll learn to manage network Security and explore backups and replications, while understanding the useful extensions of PostgreSQL so that you can optimize the speed and performance of large databases. By the end of this book, you will be able to use your database to its utmost capacity by implementing advanced administrative tasks with ease. What you will learn Get to grips with advanced PostgreSQL 11 features and SQL functions Make use of the indexing features in PostgreSQL and fine-tune the performance of your queries Work with stored procedures and manage backup and recovery Master replication and failover techniques Troubleshoot your PostgreSQL instance for solutions to common and not-so-common problems Perform database migration from MySQL and Oracle to PostgreSQL with ease Who this book is forThis book is for data and database professionals wanting to implement advanced functionalities and master complex administrative tasks with PostgreSQL 11. Prior experience of database Administration with PostgreSQL database will aid in understanding the concepts covered in this book." ,
        price : "938" ,
        author : "	Hans-Jurgen Schonig" ,
        whyData : "Why you should read Mastering PostgreSQL 11: Expert techniques to build scalable, reliable, and fault-tolerant database applications, 2nd Edition by Hans-Jurgen Schonig" ,
        whyDetails : "This book has been written by Hans-Jurgen Schonig, who has written books like Mastering PostgreSQL 12: Advanced techniques to build and administer scalable and reliable PostgreSQL database applications, 3rd Edition,Mastering PostgreSQL 11: Expert techniques to build scalable, reliable, and fault-tolerant database applications, 2nd Edition. The books are written in Computer Science,Databases category. This book is read by people who are interested in reading books in category : Databases. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Mastering PostgreSQL 11: Expert techniques to build scalable, reliable, and fault-tolerant database applications, 2nd Edition" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/410qlHBzkML.jpg" ,
        head1 : "Consciousness: A Ladybird Expert Book (Ladybird Expert Series)" ,
        head2 : "Hannah Critchlow's Consciousness: A Ladybird Expert Book (Ladybird Expert Series)" ,
        details : "Part of the new Ladybird Expert series, Consciousness is a clear, simple and Entertaining introduction to one of life's most interesting questions: what does it mean to be conscious? Written by celebrated neurologist and neuropsychologist Dr Hannah Critchlow, Consciousness will take you on a voyage to discover what allows the grey matter in our skulls to produce such complex emotions, personality traits, thoughts and memories. Written by the leading lights and most outstanding communicators in their fields, the Ladybird Expert Books provide clear, accessible and authoritative introductions to subjects drawn from science, History and culture. For an Adult readership, the Ladybird Expert series is produced in the same iconic small hardback format pioneered by the original Ladybirds. Each beautifully illustrated book features the first new illustrations produced in the original Ladybird style for nearly forty years." ,
        price : "493" ,
        author : "	Hannah Critchlow" ,
        whyData : "Why you should read Consciousness: A Ladybird Expert Book (Ladybird Expert Series) by Hannah Critchlow" ,
        whyDetails : "This book has been written by Hannah Critchlow, who has written books like The Science of Fate: Why Your Future is More Predictable Than You Think,Consciousness: A Ladybird Expert Book (Ladybird Expert Series). The books are written in Biology & Life Sciences category. This book is read by people who are interested in reading books in category : Biology & Life Sciences. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Consciousness: A Ladybird Expert Book (Ladybird Expert Series)" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41mRNfqSO5L.jpg" ,
        head1 : "Human: Solving the global workforce crisis in healthcare" ,
        head2 : "Mark Britnell's Human: Solving the global workforce crisis in healthcare" ,
        details : "By 2030, the World will be short of approximately 15 million Health workers - a fifth of the workforce needed to keep Healthcare Systems going. Global Healthcare leader and award-winning author, Dr Mark Britnell, uses his unique insights from advising governments, executives, and clinicians in more than 70 countries, to present solutions to this impending crisis. Human: Solving the Global Workforce Crisis in Healthcare, calls for a reframing of the global debate about Health and national wealth, and invites us to deal with this problem in new and adaptive ways that drive economic and human prosperity. Harnessing technology, it asks us to reimagine new Models of care and Levels of workforce agility. Drawing on experiences ranging from the world's most advanced hospitals to Revolutionary new approaches in India and Africa, Dr Mark Britnell makes it clear what works - and what does not. Short and concise, this book gives a truly global perspective on the fundamental workforce Issues facing Health Systems today." ,
        price : "1010" ,
        author : "	Mark Britnell" ,
        whyData : "Why you should read Human: Solving the global workforce crisis in healthcare by Mark Britnell" ,
        whyDetails : "This book has been written by Mark Britnell, who has written books like Human: Solving the global workforce crisis in healthcare,In Search of the Perfect Health System. The books are written in Health Care Delivery,Healthy Living & Wellness category. This book is read by people who are interested in reading books in category : Health Care Delivery. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Human: Solving the global workforce crisis in healthcare" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/410qlHBzkML.jpg" ,
        head1 : "Consciousness: A Ladybird Expert Book (Ladybird Expert Series)" ,
        head2 : " Hannah Critchlow's Consciousness: A Ladybird Expert Book (Ladybird Expert Series) " ,
        details : " Part of the new Ladybird Expert series, Consciousness is a clear, simple and Entertaining introduction to one of life's most interesting questions: what does it mean to be conscious? Written by celebrated neurologist and neuropsychologist Dr Hannah Critchlow, Consciousness will take you on a voyage to discover what allows the grey matter in our skulls to produce such complex emotions, personality traits, thoughts and memories. Written by the leading lights and most outstanding communicators in their fields, the Ladybird Expert Books provide clear, accessible and authoritative introductions to subjects drawn from science, History and culture. For an Adult readership, the Ladybird Expert series is produced in the same iconic small hardback format pioneered by the original Ladybirds. Each beautifully illustrated book features the first new illustrations produced in the original Ladybird style for nearly forty years." ,
        price : " 493" ,
        author : "	Hannah Critchlow " ,
        whyData : " Why you should read Consciousness: A Ladybird Expert Book (Ladybird Expert Series) by Hannah Critchlow " ,
        whyDetails : " This book has been written by Hannah Critchlow, who has written books like The Science of Fate: Why Your Future is More Predictable Than You Think,Consciousness: A Ladybird Expert Book (Ladybird Expert Series). The books are written in Biology & Life Sciences category. This book is read by people who are interested in reading books in category : Biology & Life Sciences. So, if you want to explore books similar to This book, you must read and buy this book. " ,
        howData : " How long would it take for you to read Consciousness: A Ladybird Expert Book (Ladybird Expert Series) " ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51JCsDuFFYL.jpg" ,
        head1 : "Haunted by Chaos: China’s Grand Strategy from Mao Zedong to Xi Jinping" ,
        head2 : "Sulmaan Wasif Khan's Haunted by Chaos: China’s Grand Strategy from Mao Zedong to Xi Jinping" ,
        details : "Before the Chinese communist party came to power, China lay broken and fragmented. Today it is a force on the global stage and yet its leaders have continued to be haunted by the past. Drawing on an array of sources, Sulmaan Wasif khan chronicles the grand strategies that have sought not only to protect china from aggression but also to ensure it would never again experience the powerlessness of the late Qing and republican eras.The dramatic variations in China’s modern History have obscured the commonality of purpose that binds the country’s leaders. Analysing the Calculus behind their decision making, Khan explores how they wove diplomatic, Military and economic power together to keep a fragile country safe in a World they saw as hostile. Dangerous and shrewd, Mao Zedong made China whole and succeeded in keeping it so, while the caustic, impatient Deng Xiaoping dragged China into the modern world. Jiang Zemin and Hu Jintao served as cautious custodians of the Deng legacy, but the powerful and deeply insecure Xi Jinping has shown an assertiveness that has raised both fear and hope across the globe.For all their considerable costs, China’s grand strategies have been largely successful. But the country faces great challenges today. Its population is aging, its Government is undermined by corruption, its neighbours are arming out of concern over its growing power and environmental degradation threatens catastrophe. A question haunted by chaos raises is whether China’s time-tested approach can respond to the looming threats of the twenty-first century." ,
        price : "475" ,
        author : "	Sulmaan Wasif Khan " ,
        whyData : "Why you should read Haunted by Chaos: China’s Grand Strategy from Mao Zedong to Xi Jinping by Sulmaan Wasif Khan" ,
        whyDetails : "This book has been written by Sulmaan Wasif Khan, who has written books like Haunted by Chaos: China’s Grand Strategy from Mao Zedong to Xi Jinping. The books are written in Government category. This book is read by people who are interested in reading books in category : Government. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51E6orTVBtL.jpg" ,
        head1 : "Experience, Caste, and the Everyday Social" ,
        head2 : "Gopal Guru's Experience, Caste, and the Everyday Social",
        details : "Experience, caste, and the everyday social offers a sustained argument that the social is experienced in various ways, through the senses as well as through conceptualizations such as self, time, and friendship. By looking at the experiences of everyday life In societies like India, It attempts to understand how different socialities are formed and sustained. It offers new insights on themes such as the ontology of the social, the way the social is experienced, the nature of social that operates in the world as invisible authority, along with the creation of notions such as social self and social time. Endorsing the concept of ‘Maitri’, signifying ethical relationship among multiple social entities, the book offers a distinct Theory of the social supported by ample empirical observations.Experience, caste, and the everyday social offers a sustained argument that the social is experienced in various ways, through the senses as well as through conceptualizations such as self, time, and friendship. By looking at the experiences of everyday life In societies like India, It attempts to understand how different socialities are formed and sustained. It offers new insights on themes such as the ontology of the social, the way the social is experienced, the nature of social that operates in the world as invisible authority, along with the creation of notions such as social self and social time. Endorsing the concept of ‘Maitri’, signifying ethical relationship among multiple social entities, the book offers a distinct Theory of the social supported by ample empirical observations." ,
        price : "849" ,
        author : "	Gopal Guru" ,
        whyData : " Why you should read Experience, Caste, and the Everyday Social by Gopal Guru" ,
        whyDetails : " This book has been written by Gopal Guru, who has written books like Humiliation: Claims and Context,Experience, Caste, and the Everyday Social,Varchasva Ani Samajik Chikitsa,The Cracked Mirror: An Indian Debate on Experience and Theory. The books are written in Political Theory,Language, Linguistics & Writing,Social Welfare & Social Services,Public Administration category. This book is read by people who are interested in reading books in category : Language, Linguistics & Writing. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Experience, Caste, and the Everyday Social" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51xvXNm7XqL.jpg" ,
        head1 : "Sincerity" ,
        head2 : "Carol Ann Duffy's Sincerity" ,
        details : "Her final collection as Poet Laureate, a frank, disarming and deeply moving exploration of loss and remembrance in their many forms. Presented in a beautiful, foiled package, this will be the Poetry book of the year." ,
        price : "334" ,
        author : "	Carol Ann Duffy" ,
        whyData : "Why you should read Sincerity by Carol Ann Duffy" ,
        whyDetails : "This book has been written by Carol Ann Duffy, who has written books like Sincerity,Collected Poems,Jubilee Lines,New Selected Poems: 1984 - 2004,Mrs Scrooge: A Christmas Tale. The books are written in Poetry,Books category. This book is read by people who are interested in reading books in category : Poetry. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Sincerity" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/5158u2YOnyL.jpg" ,
        head1 : "Lonely Planet Rajasthan, Delhi & Agra (Travel Guide)" ,
        head2 : "Lonely Planet's Lonely Planet Rajasthan, Delhi & Agra (Travel Guide)" ,
        details : "Lonely Planet Rajasthan, Delhi and Agra is your passport to the most relevant, up-to-date Advice on what to see and skip and what hidden discoveries await you. Lose yourself in the maze-like bazaars of Old Delhi, watch the sunset at the Taj Mahal, or search for tigers in Ranthambhore National Park; all with your trusted Travel companion. Get to the heart of Rajasthan, Delhi and Agra and begin your journey now!Inside Lonely Planet Rajasthan, Delhi and Agra Travel Guide:Colour Maps and images throughoutHighlights and itineraries help you tailor your trip to your Personal needs and interestsInsider Tips to save Time and money and get around like a local, avoiding crowds and trouble spotsEssential info at your fingertips - hours of operation, phone numbers, websites, transit tips, pricesHonest reviews for all budgets - eating, sleeping, sight-seeing, going out, shopping, hidden gems that most guidebooks missCultural insights give you a richer, more rewarding Travel experience - history, religion, cuisine, architecture, Arts and crafts, wildlife, environment, culture, festivalsFree, convenient pull-out Delhi map (included in print version), plus over 30 mapsCovers Delhi, Greater Delhi, Jaisalmer, Pushkar, Jodhpur, Udaipur, Jaipur, Bundi, Shekhawati, Agra, Fatehpur Sikri and moreThe Perfect Choice: Lonely Planet Rajasthan, Delhi and Agra, our most comprehensive guide to Rajasthan, Delhi and Agra, is perfect for both exploring top sights and taking roads less Travelled.Looking for more extensive coverage? Check out Lonely Planet India guide for a comprehensive look at all the country has to offer; or Best of India, a photo-rich guide to the country's most popular attractions." ,
        price : "796" ,
        author : "Lonely Planet" ,
        whyData : "Why you should read Lonely Planet Rajasthan, Delhi & Agra (Travel Guide) by Lonely Planet" ,
        whyDetails : "This book has been written by Lonely Planet, who has written books like Lonely Planet Pocket Warsaw,Lonely Planet Mauritius, Reunion & Seychelles (Travel Guide),Lonely Planet Best of Canada (Travel Guide),Lonely Planet Portugal (Travel Guide),Lonely Planet Nicaragua (Travel Guide). The books are written in Travel & Holiday Guides,Surfing, Windsurfing & Water Skiing category. This book is read by people who are interested in reading books in category : Travel & Holiday Guides. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Lonely Planet Rajasthan, Delhi & Agra (Travel Guide)" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51PnkncLJML.jpg" ,
        head1 : "World Cup 2018: The Ultimate Guide for Armchair Fans" ,
        head2 : "Lloyd Pettiford's World Cup 2018: The Ultimate Guide for Armchair Fans" ,
        details : "YOUR COMPLETE GUIDE TO THE WORLD CUP 2018! This book makes a convincing case for not travelling to Russia for the World Cup, but rather staying at Home and reading all about it. It dissects the qualifying campaign and groups, and also has a History of the World Cup with some surprising facts. Then there's a complete list of Fixtures which has already printed England in the final to save you a bit of time. It even looks forward to Qatar 2022 and suggests it might not be so bad after all. Written by the Football enthusiasts who brought you The Premier League : 25 Years and Euro 2016, it has enough facts to inform, enough laughs to impress even Sir Alex, and the answers to many questions, some of which you may even want to know the answers to, including: Why do Germany wear 4 stars on their Shirts even though a country of that name has only won the World Cup once? Is Eduard Streltsov the best Footballer you've never heard of? What naughty thing will Suarez do this time? Which team has the best kit? Which team went out at the last 16 stage of the last 5 consecutive World Cups? So settle back and enjoy the ultimate guide to the World Cup 2018 - perfect for every Football fan!" ,
        price : "401" ,
        author : "	Lloyd Pettiford" ,
        whyData : "Why you should read World Cup 2018: The Ultimate Guide for Armchair Fans by Lloyd Pettiford" ,
        whyDetails : "This book has been written by Lloyd Pettiford, who has written books like World Cup 2018: The Ultimate Guide for Armchair Fans. The books are written in Soccer category. This book is read by people who are interested in reading books in category : Soccer. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read World Cup 2018: The Ultimate Guide for Armchair Fans" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51kVPmiA9yL.jpg" ,
        head1 : "Creations FunTools Moulds For Clay & Dough 11 Pcs, 10 Small Moulds & 1 Roller." ,
        head2 : "" ,
        details : "Creations FunTools Moulds For Clay & Dough 11 Pcs, 10 Small Moulds & 1 Roller." ,
        price : "127" ,
        author : "" ,
        whyData : "" ,
        whyDetails : "" ,
        howData : "" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41j5fJuo3CL.jpg" ,
        head1 : "Raksha Bandhan Special Edition 1 Parker Vector Roller Ball Pen with Chrome Trim With Rakhi and Roli" ,
        head2 : "" ,
        details : "Rakhis on Rakshabandhan are extremely special as they celebrate an ever lasting bond that you share with your sibling. Celebrate this auspicious festival of Rakhi with love and happiness by gifting your brother Designer Rakh with Parker Pen. No sketches or graphs are made, but the designs are verbally pre decided.Certain colors are specifically inserted to make the rakhi auspicious, pristine and sacrosant. Most of the designs follow age old saga of love, trust and affection between a brother and sister." ,
        price : "315" ,
        author : "" ,
        whyData : "" ,
        whyDetails : "" ,
        howData : "" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41Qi7INpCLL.jpg" ,
        head1 : "Zaid Collections High Speed Pyraminx Stickerless Triangle Rubik Cube Puzzle" ,
        head2 : "" ,
        details : "Pyraminx Speed Cube Stickerless is the classic colour-matching puzzle that's a great mental challenge at Home or on the move. Turn and twist the sides of the cube so that each of the four faces only has one colour.Suitable for beginner and Professional player. Great corner cutting, Tension adjustable. It doesn't corner twist as often nor does it lock up. Difficult to pop, good control of the cube, comes pre-lubricated and tensioned. Definitely a good choice for you to improve Personal record in competitions. This cube can be used for international competitions. Combines high performance designs with good value. The stickerless pyramid never requires stickers, Crafted with original and eco-friendly ABS material, non-toxic, reliable, and lightweight and comfortable in the hand, harmless to human and environment. It is a classic color-matching puzzle in which the colour shift making it look like a mess, but once you solve it, it magically becomes perfect cube again. Improved anti-pop Technology and structure for extremely fast and smooth cornering. With lots of practice you can solve it in under 5 seconds! Enjoy hours of fun with you Family and friends." ,
        price : "169" ,
        author : "" ,
        whyData : "" ,
        whyDetails : "" ,
        howData : "" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51VoOhBzLHL.jpg" ,
        head1 : "Messi (Ultimate Football Heroes - Limited International Edition)" ,
        head2 : "Matt Oldfield's Messi (Ultimate Football Heroes - Limited International Edition)" ,
        details : "Complete your collection with these limited Ultimate Football Heroes International editions - now with a bonus World Cup chapter! Lionel Messi is a legend - Barcelona's star player and the world's best Footballer. But when was young, he was so small that his friends called him 'Little Leo' and coaches worried he wasn't big enough. Yet through bravery, talent and hard work, he proved them wrong. Messi tells the magical story of how the tiniest boy in South America grew up to become the greatest player on earth." ,
        price : "160" ,
        author : "	Matt Oldfield" ,
        whyData : "Why you should read Messi (Ultimate Football Heroes - Limited International Edition) by Matt Oldfield" ,
        whyDetails : "This book has been written by Matt Oldfield, who has written books like Van Dijk (Ultimate Football Heroes),De Bruyne - Collect Them All! (Ultimate Football Heroes),Salah (Ultimate Football Heroes),Kane (Ultimate Football Heroes - International Edition),Figo (Classic Football Heroes - Limited International Edition). The books are written in Sport category. This book is read by people who are interested in reading books in category : Sport. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Messi (Ultimate Football Heroes - Limited International Edition)" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51PrGj2zyVL.jpg" ,
        head1 : "Hematology and Coagulation: A Comprehensive Review for Board Preparation, Certification and Clinical Practice" ,
        head2 : "Amer Wahed's Hematology and Coagulation: A Comprehensive Review for Board Preparation, Certification and Clinical Practice" ,
        details : "Hematology and Coagulation: A Comprehensive Review for Board Preparation, Certification and Clinical Practice, Second Edition, takes a practical and easy-to-read approach to understanding Hematology and coagulation at an appropriate level for both board preparation and refresher courses. The book bridges the gap between large textBooks and medical technology Books written for laboratory technicians, providing the sufficient background in genetics, Toxicology and Immunology that residents and medical students need to know in order to become successful physicians. Readers will use this quick Reference to understand how tests are performed and how to interpret results. This clear and easy-to-read presentation of core topics and detailed case studies illustrates the application of hematopathology on patient care." ,
        price : "7498" ,
        author : "	Amer Wahed" ,
        whyData : "Why you should read Hematology and Coagulation: A Comprehensive Review for Board Preparation, Certification and Clinical Practice by Amer Wahed" ,
        whyDetails : "This book has been written by Amer Wahed, who has written books like Hematology and Coagulation: A Comprehensive Review for Board Preparation, Certification and Clinical Practice,Hematopathology and Coagulation: Questions, Answers and Explanations. The books are written in Biology & Life Sciences,Pathology category. This book is read by people who are interested in reading books in category : Biology & Life Sciences. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Hematology and Coagulation: A Comprehensive Review for Board Preparation, Certification and Clinical Practice" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51yTse%2BHDXL.jpg" ,
        head1 : "Reasoning, Maths and Science Olympiad Workbook Combo - Class 6" ,
        head2 : "Swastick Book Box's Reasoning, Maths and Science Olympiad Workbook Combo - Class 6" ,
        details : "SBB Olympiad Workbooks help students to prepare for Olympiad exams through meticulously designed contents. The Workbooks help the child to focus on the basics of the subject and promotes logical brain development that improves child overall logical thought process and problem-solving skills. SBB Logical Reasoning, Science and Mathematics Olympiad Workbooks are a complete preparatory set for Olympiads. For better results in exams, Books also contain past years questions from various Olympiads. The Books are based on NCERT/CBSE/ICSE/IGCSE/IB/state-board syllabus so its complete preparatory set for Class 6 as well. Reasoning as a subject has an independent olympiad exam as well as a mandatory part of Science, Maths and Cyber Olympiad exams and make this combo a perfect buy for winning a medal in Science, Maths and Reasoning Olympiads." ,
        price : "237" ,
        author : "	Swastick Book Box" ,
        whyData : "Why you should read Reasoning, Maths and Science Olympiad Workbook Combo - Class 6 by Swastick Book Box" ,
        whyDetails : "This book has been written by Swastick Book Box, who has written books like Reasoning, Maths, Science and English Olympiad Workbook Combo - Class 5,Reasoning, Maths, Science, Cyber, English & GK Olympiad Workbook Combo - Class 3,Reasoning, Maths, Science and English Olympiad Workbook Combo - Class 2,Reasoning, Maths, Science, Cyber, English & GK Olympiad Workbook Combo - Class 4,SBB - Writing Practice Books [Set of 6]. The books are written in Olympiads & Scholarship Exams,Early Learning category. This book is read by people who are interested in reading books in category : Olympiads & Scholarship Exams. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51GSXEes5pL.jpg" ,
        head1 : "How to Sail Through the Ukcat: Master the UK Clincal Aptitude Test: The Ultimate Cheat Sheet" ,
        head2 : "Morgan Phillips's How to Sail Through the Ukcat: Master the UK Clincal Aptitude Test: The Ultimate Cheat Sheet" ,
        details : "Each year, students experience difficulty preparing for the UKCAT - despite the wealth of avaibable information including: Online courses, Literature, Question guides and Crash-courses. The format of the UKCAT has not changed, but the average performance - and expectations from Medical and Dental schools - is on the rise. In short, the stakes are rising. 'How to Sail Through the UKCAT' condenses fail-safe strategies adopted by the strongest UKCAT applicants, into an informative read - including activities, answer guides, Advice and further reading resouces. You don't need to know much to ACE the UKCAT, but you do need to know how to approach it. Learn the secrets to scoring in the Top percentile with this bona fide no-waffle cheat sheet!" ,
        price : "664" ,
        author : "	Morgan Phillips" ,
        whyData : "Why you should read How to Sail Through the Ukcat: Master the UK Clincal Aptitude Test: The Ultimate Cheat Sheet by Morgan Phillips" ,
        whyDetails : "This book has been written by Morgan Phillips, who has written books like How to Sail Through the Ukcat: Master the UK Clincal Aptitude Test: The Ultimate Cheat Sheet. The books are written in Medicine category. This book is read by people who are interested in reading books in category : Medicine. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read How to Sail Through the Ukcat: Master the UK Clincal Aptitude Test: The Ultimate Cheat Sheet" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51K7fwdkscL.jpg" ,
        head1 : "Our Towns: A 100,000-Mile Journey into the Heart of America" ,
        head2 : "James Fallows's Our Towns: A 100,000-Mile Journey into the Heart of America" ,
        details : "***NATIONAL BEST SELLER***A vivid, surprising portrait of the civic and economic reinvention taking place in America, town by town and generally out of view of the national media. A realistically positive and provocative view of the country between its coasts. For the last five years, James and Deborah Fallows have been traveling across America in a single-engine prop airplane. Visiting dozens of towns, they have met hundreds of civic leaders, workers, immigrants, educators, environmentalists, artists, public servants, librarians, Business people, city planners, students, and entrepreneurs to take the pulse and understand the prospects of places that usually draw notice only after a disaster or during a political campaign. The America they saw is acutely conscious of its problems—from economic dislocation to the opioid scourge—but itis also Crafting solutions, with a practical-minded determination at dramatic odds with the bitter paralysis of national politics. At times of dysfunction on a national level, reform possibilities have often arisen from the local level. The Fallowses describe America in the middle of one of these creative waves. Their view of the country is as complex and contradictory as America itself, but it also reflects the energy, the generosity and compassion, the dreams, and the determination of many who are in the midst of making things better. Our Towns is the story of their journey—and an account of a country busy remaking itself." ,
        price : "1054" ,
        author : "	James Fallows" ,
        whyData : "Why you should read Our Towns: A 100,000-Mile Journey into the Heart of America by James Fallows" ,
        whyDetails : "This book has been written by James Fallows, who has written books like Our Towns: A 100,000-Mile Journey into the Heart of America,China Airborne: The Test of China's Future,Blind Into Baghdad: America's War in Iraq,Looking at the Sun: The Rise of the New East Asian Economic and Political System,Breaking The News: How the Media Undermine American Democracy. The books are written in Anthropology,Business & Economics,International Relations & Globalization,Economics,Political Structure & Processes category. This book is read by people who are interested in reading books in category : Anthropology. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Our Towns: A 100,000-Mile Journey into the Heart of America" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51Jtk6wjjTL.jpg" ,
        head1 : "Love Unexpected" ,
        head2 : "Ritu Kakar's Love Unexpected" ,
        details : "Kaira is an independent girl, chasing her ambitions. Aveer is a strong-minded and successful entrepreneur, seeking expansion. When they get together to give wings to her venture, there are fireworks and a strange Chemistry between them. But there is something else walking along – kaira’s past. With drew’s presence looming large like the devil, kaira does not know how to accept her emotions for aveer. Her loved ones protect her from all harm fiercely, but will they succeed this time too? Amidst confusion of a promising future and the demons of the past, in trying to find faith and burying betrayal, and in the battle between kaira’s heart and her fears will love unexpected lead the way to happiness?." ,
        price : "135" ,
        author : "	Ritu Kakar" ,
        whyData : "Why you should read Love Unexpected by Ritu Kakar" ,
        whyDetails : "This book has been written by Ritu Kakar, who has written books like Love Unexpected. The books are written in Indian Writing category. This book is read by people who are interested in reading books in category : Indian Writing. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Love Unexpected" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/415AcfkPiZL.jpg" ,
        head1 : "Rubiks Cube TamBoora Dul Dul High Stability Sticker Less Smooth Swing 3X3X3 Speed Cube for Faster Movement (Medium Size)" ,
        head2 : "" ,
        details : "Tamboora speed cube for high stability smooth movement for faster performance and durability specially designed for masterminds by Dul Dul. Good Quality" ,
        price : "109" ,
        author : "" ,
        whyData : "" ,
        whyDetails : "" ,
        howData : "" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/51ruxbcny7L.jpg" ,
        head1 : "Ballots and Breakups: The Games Politicians Play" ,
        head2 : "Sunita Aron's Ballots and Breakups: The Games Politicians Play" ,
        details : "Winning elections is not everything, what is crucial for the good health of a robust democracy is forming a Government.From strategically devised pre-poll alliances to hastily stitched together post-poll associations, noted journalist Sunita Aron has travelled the length and breadth of the country, painstakingly documenting the Drama and dharma of coalition Politics in India. The result of her exhaustive research and insightful analysis, Ballots and Breakups is a cracker of a read. As Indian voters deliver fractured verdicts, political parties resort to constructing fragile coalitions by hook or by crook. The hapless casualties of this relentless quest for power are the Indian voters and this book is for them, as the writer eloquently exhorts for the need of common guidelines on the formation of a Government in the case of a hung house. A gripping take on coalition Politics in India, Aron charts a riveting tale of modern Indian Politics that has all the masala of a Bollywood potboiler, but the ending, the writer asserts, has to be happy like that of any Hindi film, 'stable Governments and a prosperous society even in a hung house!'" ,
        price : "273" ,
        author : "Sunita Aron" ,
        whyData : "Why you should read Ballots and Breakups: The Games Politicians Play by Sunita Aron" ,
        whyDetails : "This book has been written by Sunita Aron, who has written books like Ballots and Breakups: The Games Politicians Play,Akhilesh Yadav: Winds of Change. The books are written in Political Ideologies,Biographies, Diaries & True Accounts category. This book is read by people who are interested in reading books in category : Political Ideologies. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read Ballots and Breakups: The Games Politicians Play" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41MuYMBkiZL.jpg" ,
        head1 : "The Principles of Sufism" ,
        head2 : "'A'ishah AL-Ba'Uniyyah's The Principles of Sufism" ,
        details : "The Principles of Sufism is a mystical guide book to help others on their spiritual path. Outlining the four principles of Repentance, Sincerity, Remembrance and Love, it traces the fundamental stages and states of the spiritual novice’s transformative journey, emphasizing the importance of embracing both human limitations and God’s limitless love. Drawing on lessons and readings from centuries-old Sufi tradition, ‘A’ishah advises the seeker to repent of selfishness and turn to a sincere life of love. In addition to his lucid translation, Th. Emil Homerin provides an insightful introduction, notes and a glossary to ‘A’ishah al-Ba‘uniyyah’s remarkable account of the pursuit of mystical illumination.‘A’ishah al-Ba‘uniyyah of Damascus was one of the great Women scholars in Islamic history. Born into a prominent Family of pious scholars and Sufi devotees, ‘A’ishah received a thorough Religious Education and memorized the Quran at age eight. A mystic and a prolific poet and writer, she composed more works in Arabic than any other woman before the twentieth century.Yet despite her extraordinary Literary and Religious achievements, ‘A’ishah al- Ba‘uniyyah remains largely unknown. For the first time, her key work, the Principles of Sufism, is available in English translation." ,
        price : "190" ,
        author : "	'A'ishah AL-Ba'Uniyyah" ,
        whyData : "Why you should read The Principles of Sufism by 'A'ishah AL-Ba'Uniyyah" ,
        whyDetails : "This book has been written by 'A'ishah AL-Ba'Uniyyah, who has written books like The Principles of Sufism. The books are written in Theology & Philosophy of Religion category. This book is read by people who are interested in reading books in category : Theology & Philosophy of Religion. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData : "How long would it take for you to read The Principles of Sufism" ,
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41GL-d%2BSEwL.jpg" ,
        head1 : "Intensive Transactional Analysis Psychotherapy: An Integrated Model" ,
        head2 : "Marco Sambin's Intensive Transactional Analysis Psychotherapy: An Integrated Model" ,
        details : "Intensive Transactional Analysis Psychotherapy: An Integrated Model (ITAP) introduces a new approach of Psychotherapy. Based on psychoDynamic foundations, the ITAP integrates the most recent trends in short-term Dynamic Psychotherapy and Transactional Analysis. This book develops an innovative, clear and complete Clinical model of ITAP, and introduces the reader, step-by-step, to the theoretical basis underlying the technique of this intervention. The authors introduce the therapeutic procedure by bringing together the Theory with brief Clinical examples, thereby demonstrating the attitude of the intense therapist as well as which theoretical pathways to take to progress with the patient. In addition to the modulation of the technique based on the level of the patient’s suffering, there is also a systematic examination of which cases should be treated with ITAP, and in what way. Intensive Transactional Analysis Psychotherapy is a therapy which can be easily used by all therapists, and this book will be of great Interest to Transactional Analysis therapists and other therapists Interested in Transactional Analysis and short-term Dynamic Psychotherapy." ,
        price : "2008" ,
        author : "	Marco Sambin" ,
        whyData : "Why you should read Intensive Transactional Analysis Psychotherapy: An Integrated Model by Marco Sambin" ,
        whyDetails : "This book has been written by Marco Sambin, who has written books like Intensive Transactional Analysis Psychotherapy: An Integrated Model. The books are written in Social Welfare & Social Services category. This book is read by people who are interested in reading books in category : Social Welfare & Social Services. So, if you want to explore books similar to This book, you must read and buy this book." ,
        howData :"How long would it take for you to read Intensive Transactional Analysis Psychotherapy: An Integrated Model",
    },

    {
        imgUrl : "https://images-eu.ssl-images-amazon.com/images/I/41olnwqfFXL.jpg",
        head1 : "Comprehensive Electromyography: With Clinical Correlations and Case Studies",
        head2 : "Mark A. Ferrante's Comprehensive Electromyography: With Clinical Correlations and Case Studies",
        details : "Electromyography (EMG) is a technique for evaluating and recording the Electrical activity produced by nerves and muscles. Interpreting EMG is a mandatory skill for neurologists and rehabilitation specialists. This textbook provides the reader with a detailed discussion of the concepts and principles underlying electrodiagnostic medicine. It is written for an audience without pre-existing knowledge in this discipline, including beginner technicians and physicians in training. It is an ideal review for seasoned practitioners and those preparing for board examinations. It begins with a review of the foundational sciences and works through the field in twenty chapters, including a large number of case studies demonstrating correct application and interpretation. Appendices of information frequently required in the EMG laboratory, such as Nerve Conduction Study techniques and their age-related normal values, anatomic regions assessed by each NCS and needle EMG studies, Safety issues, and other important topics, are also included.",
        price : "4265",
        author : "	Mark A. Ferrante",
        whyData : "Why you should read Comprehensive Electromyography: With Clinical Correlations and Case Studies by Mark A. Ferrante",
        whyDetails :"This book has been written by Mark A. Ferrante, who has written books like Comprehensive Electromyography: With Clinical Correlations and Case Studies. The books are written in Neurology category. This book is read by people who are interested in reading books in category : Neurology. So, if you want to explore books similar to This book, you must read and buy this book.",
        howData : "How long would it take for you to read Comprehensive Electromyography: With Clinical Correlations and Case Studies",
    },
] ;

localStorage.setItem("rawData",JSON.stringify(dataArr)) ;